# TOML document to store filters

[longtalk_make_reservation]

    # Size of the room: How many people ?
    [longtalk_make_reservation.people]
    words = ["pearson", "people"]
    regex = '''(?P<people>\d)\W%s'''
    threshold = 0.85

    # Duration of the book: How long ?
    [longtalk_make_reservation.duration]
    words = ["day", "night"]
    regex = '''(?P<duration>\d)\W%s'''
    threshold = 0.85
